# Generated by Django 4.2.1 on 2023-08-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("smile_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("abstract", models.CharField(max_length=255)),
                ("box_url", models.URLField(max_length=255)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("categories", models.ManyToManyField(to="api.category")),
            ],
        ),
    ]
