# Generated by Django 4.2.1 on 2023-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="readers_number",
            field=models.IntegerField(null=True),
        ),
    ]
