# Generated by Django 4.2.1 on 2023-08-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_report_authors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="authors",
            new_name="author",
        ),
    ]
