# Generated by Django 4.2.1 on 2023-08-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_report_readers_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="reader",
            new_name="readers",
        ),
    ]
