# Generated by Django 4.2.1 on 2023-08-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_reader_report_readers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="categories",
            field=models.ManyToManyField(null=True, to="api.category"),
        ),
    ]
