# Generated by Django 4.2.1 on 2023-08-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_report_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="api.category"),
        ),
    ]
