# Generated by Django 4.2.1 on 2023-08-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_report_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="categories",
            field=models.ManyToManyField(blank=True, to="api.category"),
        ),
        migrations.AlterField(
            model_name="report",
            name="readers_number",
            field=models.IntegerField(default=0),
        ),
    ]
